### ISSUE TITLE
Game crashes upon opening inventory

### ISSUE THREAD

**Issue by tj-cool** [seymourimadeit/guardvillagers#106]
I tried to open the inventory in creative mode, and the game froze, then saved and quit the world.
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-01-27 19:02:57
Description: Unexpected error

net.minecraftforge.fml.ModLoadingException: Guard Villagers (guardvillagers) encountered an error during the done event phase
§7java.lang.NoSuchMethodError: 'void net.minecraftforge.event.CreativeModeTabEvent$BuildContents.m_246326_(net.minecraft.world.level.ItemLike)'
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:111) ~[javafmllanguage-1.19.3-44.0.5.jar%23160!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$postEventWithReturn$35(ModLoader.java:319) ~[fmlcore-1.19.3-44.0.5.jar%23159!/:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {}
	at net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:225) ~[fmlcore-1.19.3-44.0.5.jar%23159!/:?] {}
	at net.minecraftforge.fml.ModLoader.postEventWithReturn(ModLoader.java:319) ~[fmlcore-1.19.3-44.0.5.jar%23159!/:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onCreativeModeTabBuildContents(ForgeHooksClient.java:1194) ~[forge-1.19.3-44.0.5-universal.jar%23163!/:?] {re:classloading}
	at net.minecraft.world.item.CreativeModeTab.m_258021_(CreativeModeTab.java:111) ~[client-1.19.3-20221207.122022-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.item.CreativeModeTabs.m_257611_(CreativeModeTabs.java:1553) ~[client-1.19.3-20221207.122022-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraft.world.item.CreativeModeTabs.m_257534_(CreativeModeTabs.java:1552) ~[client-1.19.3-20221207.122022-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.item.CreativeModeTabs.m_257580_(CreativeModeTabs.java:1572) ~[client-1.19.3-20221207.122022-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.<init>(CreativeModeInventoryScreen.java:88) ~[client-1.19.3-20221207.122022-srg.jar%23158!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.InventoryScreen.m_7856_(InventoryScreen.java:50) ~[client-1.19.3-20221207.122022-srg.jar%23158!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_232761_(Screen.java:429) ~[client-1.19.3-20221207.122022-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_6575_(Screen.java:419) ~[client-1.19.3-20221207.122022-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91152_(Minecraft.java:992) ~[client-1.19.3-20221207.122022-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1928) ~[client-1.19.3-20221207.122022-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1793) ~[client-1.19.3-20221207.122022-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1097) ~[client-1.19.3-20221207.122022-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:713) ~[client-1.19.3-20221207.122022-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[1.19.3-forge-44.0.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[1.19.3-forge-44.0.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.3-44.0.5.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
Caused by: java.lang.NoSuchMethodError: 'void net.minecraftforge.event.CreativeModeTabEvent$BuildContents.m_246326_(net.minecraft.world.level.ItemLike)'
	at tallestegg.guardvillagers.GuardVillagers.addCreativeTabs(GuardVillagers.java:48) ~[guardvillagers-1.19.3-1.5.4.jar%23156!/:1.19.3-1.5.4] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2380!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2380!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2380!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2380!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19.3-44.0.5.jar%23160!/:?] {}
	... 43 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:111) ~[javafmllanguage-1.19.3-44.0.5.jar%23160!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$postEventWithReturn$35(ModLoader.java:319) ~[fmlcore-1.19.3-44.0.5.jar%23159!/:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {}
	at net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:225) ~[fmlcore-1.19.3-44.0.5.jar%23159!/:?] {}
	at net.minecraftforge.fml.ModLoader.postEventWithReturn(ModLoader.java:319) ~[fmlcore-1.19.3-44.0.5.jar%23159!/:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onCreativeModeTabBuildContents(ForgeHooksClient.java:1194) ~[forge-1.19.3-44.0.5-universal.jar%23163!/:?] {re:classloading}
	at net.minecraft.world.item.CreativeModeTab.m_258021_(CreativeModeTab.java:111) ~[client-1.19.3-20221207.122022-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.item.CreativeModeTabs.m_257611_(CreativeModeTabs.java:1553) ~[client-1.19.3-20221207.122022-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraft.world.item.CreativeModeTabs.m_257534_(CreativeModeTabs.java:1552) ~[client-1.19.3-20221207.122022-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.item.CreativeModeTabs.m_257580_(CreativeModeTabs.java:1572) ~[client-1.19.3-20221207.122022-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.<init>(CreativeModeInventoryScreen.java:88) ~[client-1.19.3-20221207.122022-srg.jar%23158!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.InventoryScreen.m_7856_(InventoryScreen.java:50) ~[client-1.19.3-20221207.122022-srg.jar%23158!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_232761_(Screen.java:429) ~[client-1.19.3-20221207.122022-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_6575_(Screen.java:419) ~[client-1.19.3-20221207.122022-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91152_(Minecraft.java:992) ~[client-1.19.3-20221207.122022-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1928) ~[client-1.19.3-20221207.122022-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['UnsoundBeast480'/92, l='ClientLevel', x=-5.58, y=-60.00, z=13.97]]
	Chunk stats: 289, 169
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1481 game time, 1481 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:452) ~[client-1.19.3-20221207.122022-srg.jar%23158!/:?] {re:classloading,xf:OptiFine:default,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2319) ~[client-1.19.3-20221207.122022-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:735) ~[client-1.19.3-20221207.122022-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[1.19.3-forge-44.0.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[1.19.3-forge-44.0.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.3-44.0.5.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: mod_resources, vanilla

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1088349072 bytes (1037 MiB) / 1845493760 bytes (1760 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 3.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 630
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x5912
	Graphics card #0 versionInfo: DriverVersion=31.0.101.2112
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 17410.32
	Virtual memory used (MB): 10064.41
	Swap memory total (MB): 1152.00
	Swap memory used (MB): 6.28
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.19.3-forge-44.0.5
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: Intel(R) HD Graphics 630 GL version 3.2.0 - Build 31.0.101.2112, Intel
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['UnsoundBeast480'/92, l='ServerLevel[fighting villagers]', x=-5.58, y=-60.00, z=13.97]]
	Data Packs: vanilla, mod:forge, mod:guardvillagers (incompatible), mod:worldedit (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.3-44.0.5.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.3-44.0.5.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.3-44.0.5.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.3-44.0.5.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.3-44.0.5.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.3-20221207.122022-srg.jar             |Minecraft                     |minecraft                     |1.19.3              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.19.3-44.0.5-universal.jar                 |Forge                         |forge                         |44.0.5              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		guardvillagers-1.19.3-1.5.4.jar                   |Guard Villagers               |guardvillagers                |1.19.3-1.5.4        |DONE      |Manifest: NOSIGNATURE
		worldedit-mod-7.2.13.jar                          |WorldEdit                     |worldedit                     |7.2.13+46576cc      |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 9941bd52-d177-48d1-9f27-4531172c1201
	FML: 44.0
	Forge: net.minecraftforge:44.0.5

**Comment by tj-cool** [comment]
["guard stuff"]
	#This lets Guards open doors.
	"Have Guards open doors?" = true
	#This will make guards raise their shields all the time, on default they will only raise their shields under certain conditions
	"Have Guards raise their shield all the time?" = false
	#Range: -9999 ~ 9999
	"How low of a reputation of a player should have to be instantly aggroed upon by guards and golems?" = -100
	"Allow players to give guards stuff only if they have the hero of the village effect?" = false
	"Have guards only follow the player if they have hero of the village?" = true
	#Range: -500.0 ~ 900.0
	"Guard speed" = 0.5
	#This will make guards attempt to avoid friendly fire.
	"Have guards attempt to avoid firing into other friendlies? (Experimental)" = false
	#This is the range in which the guards will be aggroed to mobs that are attacking villagers. Higher values are more resource intensive, and setting this to zero will disable the goal.
	#Range: -500.0 ~ 500.0
	Range = 50.0
	#Range: > -2147483648
	"Minimum reputation requirement for guards to give you access to their inventories" = 15
	#How much health a guard regenerates.
	#Range: -500.0 ~ 500.0
	"Guard health regeneration amount" = 1.0
	#Range: 0.0 ~ 900.0
	"Guard follow range" = 20.0
	"Allow players to set guard patrol points only if they have hero of the village" = false
	#This makes Guards run from polar bears, as anyone with common sense would.
	"Have Guards have some common sense?" = false
	"Allow guard arrows to damage villagers, iron golems, or other guards? The i-frames will still be shown for them but they won't lose any health if this is set to false" = true
	#Range: -999.9000244140625 ~ 999.0
	"Chance to drop equipment" = 100.0
	#This makes guards form a phalanx
	"Have guards form a phalanx?" = true
	#Range: -500.0 ~ 900.0
	"Guard health" = 20.0

["raids and illagers"]
	#This makes Illagers run from polar bears, as anyone with common sense would.
	"Have Illagers have some common sense?" = true
	#Witches Attack Villagers?
	"Witches attack villagers?" = true
	#Illagers In Raids Attack Animals?
	"Illagers in raids attack animals?" = false
	#This will make Illusioners get involved in raids
	"Have Illusioners in raids?" = false

["mob ai in general"]
	#Guards will attack all hostiles with this option
	"Guards attack all mobs?" = false
	#Guards won't attack mobs in this list if AttackAllMobs is enabled, for example, putting "minecraft:creeper" in this list will make guards ignore creepers.
	"Mob BlackList" = []

["villager stuff"]
	#This makes villagers run from polar bears, as anyone with common sense would.
	"Have Villagers have some common sense?" = true
	"Have it so clerics heal guards and players with hero of the village?" = true
	"Allow armorers and weaponsmiths repair guard items when down below half durability?" = true
	#This will make it so villagers will only be converted into guards if the player has hero of the village
	"Make it so players have to have hero of the village to convert villagers into guards?" = false
	"Have it so blacksmiths heal golems under 60 health?" = true

**Comment by seymourimadeit** [comment]
Update your forge to the latest version. You are on a outdated version of forge. If this issue persists request a reopen.
