### ISSUE TITLE
Crash Report 

### ISSUE THREAD

**Issue by Arasarhood** [seymourimadeit/guardvillagers#116]
---- Minecraft Crash Report ----
// My bad.

Time: 4/9/23, 2:52 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.2-40.2.0-universal.jar%23119!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.18.2-40.2.0-universal.jar%23119!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220404.173914-srg.jar%23114!/:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.2.0.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.eventbus.ASMEventHandler.<init>(ASMEventHandler.java:50) ~[eventbus-5.0.3.jar%232!/:?] {}
-- MOD guardvillagers --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.2.0.jar%23116!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.2.0.jar%23115!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /F:/APWNN 2.13 with Tectonic/mods/guardvillagers-1.18.2.1.4.3.jar
	Failure message: Guard Villagers (guardvillagers) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.4.3
	Mod Issue URL: https://github.com/seymourimadeit/guardvillagers/issues
	Exception message: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getConstructor(java.lang.Class[])" because the return value of "net.minecraftforge.eventbus.ASMEventHandler.createWrapper(java.lang.reflect.Method)" is null
Stacktrace:
	at net.minecraftforge.eventbus.ASMEventHandler.<init>(ASMEventHandler.java:50) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:254) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.registerListener(EventBus.java:150) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$registerObject$6(EventBus.java:98) ~[eventbus-5.0.3.jar%232!/:?] {}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.minecraftforge.eventbus.EventBus.lambda$registerObject$7(EventBus.java:98) ~[eventbus-5.0.3.jar%232!/:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:94) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:120) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.registries.DeferredRegister.register(DeferredRegister.java:360) ~[forge-1.18.2-40.2.0-universal.jar%23119!/:?] {re:classloading}
	at tallestegg.guardvillagers.GuardVillagers.<init>(GuardVillagers.java:30) ~[guardvillagers-1.18.2.1.4.3.jar%2378!/:1.18.2.1.4.3] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.2.0.jar%23116!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.2.0.jar%23115!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1767232392 bytes (1685 MiB) / 4294967296 bytes (4096 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 42 Stepping 7
	Microarchitecture: Sandy Bridge (Client)
	Frequency (GHz): 3.41
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GT 430
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x0de1
	Graphics card #0 versionInfo: DriverVersion=23.21.13.8813
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.07
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.07
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 4096.00
	Memory slot #2 clockSpeed (GHz): 1.07
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 4096.00
	Memory slot #3 clockSpeed (GHz): 1.07
	Memory slot #3 type: DDR3
	Virtual memory max (MB): 18783.15
	Virtual memory used (MB): 11563.70
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms4G -Xmx8G
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		YungsBetterDungeons-1.18.2-Forge-2.1.0.jar        |YUNG's Better Dungeons        |betterdungeons                |1.18.2-Forge-2.1.0  |COMMON_SET|Manifest: NOSIGNATURE
		betteranimalmodels-1.18.2-5.6.0-forge.jar         |Cyber's Better Animal Models  |betteranimalmodels            |1.18.2-5.6.0        |COMMON_SET|Manifest: NOSIGNATURE
		pamhc2trees-1.18.2-1.0.3.jar                      |Pam's HarvestCraft 2 - Trees  |pamhc2trees                   |1.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		advanced-xray-forge-1.18.2-2.11.0-build.7.jar     |Advanced XRay                 |xray                          |1.18.2-2.11.0-build.|COMMON_SET|Manifest: NOSIGNATURE
		jei-1.18.2-9.5.5.174.jar                          |Just Enough Items             |jei                           |9.5.5.174           |COMMON_SET|Manifest: NOSIGNATURE
		DoggyTalents-1.18.2-2.5.11.jar                    |Doggy Talents 2               |doggytalents                  |2.5.11              |COMMON_SET|Manifest: NOSIGNATURE
		sophisticatedcore-1.18.2-0.5.37.202.jar           |Sophisticated Core            |sophisticatedcore             |1.18.2-0.5.37.202   |COMMON_SET|Manifest: NOSIGNATURE
		rubidium-0.5.4.jar                                |Rubidium                      |rubidium                      |0.5.4               |COMMON_SET|Manifest: NOSIGNATURE
		Kobolds-2.1.2.jar                                 |Kobolds                       |kobolds                       |2.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		waystones-forge-1.18.2-10.1.0.jar                 |Waystones                     |waystones                     |10.1.0              |COMMON_SET|Manifest: NOSIGNATURE
		villagernames-1.18.2-5.1.jar                      |Villager Names                |villagernames                 |5.1                 |COMMON_SET|Manifest: NOSIGNATURE
		Clumps-forge-1.18.2-8.0.0+17.jar                  |Clumps                        |clumps                        |8.0.0+17            |COMMON_SET|Manifest: NOSIGNATURE
		journeymap-1.18.2-5.9.2-forge.jar                 |Journeymap                    |journeymap                    |5.9.2               |COMMON_SET|Manifest: NOSIGNATURE
		cookingforblockheads-forge-1.18.2-12.2.0.jar      |CookingForBlockheads          |cookingforblockheads          |12.2.0              |COMMON_SET|Manifest: NOSIGNATURE
		citadel-1.11.3-1.18.2.jar                         |Citadel                       |citadel                       |1.11.3              |COMMON_SET|Manifest: NOSIGNATURE
		alexsmobs-1.18.6.jar                              |Alex's Mobs                   |alexsmobs                     |1.18.6              |COMMON_SET|Manifest: NOSIGNATURE
		configured-2.0.0-1.18.2.jar                       |Configured                    |configured                    |2.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		YungsApi-1.18.2-Forge-2.2.7.jar                   |YUNG's API                    |yungsapi                      |1.18.2-Forge-2.2.7  |COMMON_SET|Manifest: NOSIGNATURE
		BotanyPots-Forge-1.18.2-8.0.24.jar                |BotanyPots                    |botanypots                    |8.0.24              |COMMON_SET|Manifest: NOSIGNATURE
		betteranimalsplus-1.18.2-11.0.10-forge.jar        |Better Animals Plus           |betteranimalsplus             |1.18.2-11.0.10      |COMMON_SET|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.18.2-13.2.50.jar                |Bookshelf                     |bookshelf                     |13.2.50             |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		sophisticatedbackpacks-1.18.2-3.18.40.777.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.18.2-3.18.40.777  |COMMON_SET|Manifest: NOSIGNATURE
		guardvillagers-1.18.2.1.4.3.jar                   |Guard Villagers               |guardvillagers                |1.4.3               |ERROR     |Manifest: NOSIGNATURE
		balm-3.2.1+0.jar                                  |Balm                          |balm                          |3.2.1+0             |COMMON_SET|Manifest: NOSIGNATURE
		carryon-1.18.2-1.17.0.8.jar                       |Carry On                      |carryon                       |1.17.0.8            |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-6.4.90-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.4.90              |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.18.2-40.2.0-universal.jar                 |Forge                         |forge                         |40.2.0              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Waddles-1.18.2-0.8.19.jar                         |Waddles                       |waddles                       |1.18.2-0.8.19       |COMMON_SET|Manifest: NOSIGNATURE
		revampedwolf-1.18.2-1.2.0.jar                     |RevampedWolf                  |revampedwolf                  |1.18.2-1.2.0        |COMMON_SET|Manifest: NOSIGNATURE
		twilightforest-1.18.2-4.1.1423-universal.jar      |The Twilight Forest           |twilightforest                |4.1.1423            |COMMON_SET|Manifest: NOSIGNATURE
		emojiful-1.18.2-3.0.1.jar                         |Emojiful                      |emojiful                      |1.18.2-3.0.1        |COMMON_SET|Manifest: NOSIGNATURE
		NoCubes-1.18.2-0.5.0-dev-22cb4ee.jar              |NoCubes                       |nocubes                       |1.18.2-0.5.0-dev-22c|COMMON_SET|Manifest: 7b:95:cc:94:64:e7:31:77:3f:09:ab:5c:ac:fc:0f:c7:85:b1:4d:86:46:27:ee:c2:84:8c:a8:61:d8:ee:9a:c6
		DungeonsArise-1.18.2-2.1.52-release.jar           |When Dungeons Arise           |dungeons_arise                |2.1.52-1.18.2       |COMMON_SET|Manifest: NOSIGNATURE
		tectonic-mod-mc1.18.2-v1.1.4.jar                  |Tectonic                      |tectonic                      |1.1.4               |COMMON_SET|Manifest: NOSIGNATURE
		server-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |COMMON_SET|Manifest: NOSIGNATURE
		TerraBlender-forge-1.18.2-1.2.0.126.jar           |TerraBlender                  |terrablender                  |1.2.0.126           |COMMON_SET|Manifest: NOSIGNATURE
		physics-mod-pro-v141-forge-1.18.2.jar             |Physics Mod                   |physicsmod                    |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		BiomesOPlenty-1.18.2-16.0.0.109-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.18.2-16.0.0.109   |COMMON_SET|Manifest: NOSIGNATURE
		simpleshops-1.2.1.jar                             |Simple Shops                  |simpleshops                   |1.1.4               |COMMON_SET|Manifest: NOSIGNATURE
		Jade-1.18.2-forge-5.2.6.jar                       |Jade                          |jade                          |5.2.6               |COMMON_SET|Manifest: NOSIGNATURE
		pamhc2crops-1.18.2-1.0.5.jar                      |Pam's HarvestCraft 2 - Crops  |pamhc2crops                   |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		domum_ornamentum-1.18.2-1.0.77-ALPHA-universal.jar|Domum Ornamentum              |domum_ornamentum              |1.18.2-1.0.77-ALPHA |COMMON_SET|Manifest: NOSIGNATURE
		pamhc2foodextended-1.18.2-1.0.5.jar               |Pam's HarvestCraft 2 - Food Ex|pamhc2foodextended            |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		betterfpsdist-1.18.2-1.5.jar                      |betterfpsdist mod             |betterfpsdist                 |1.18.2-1.5          |COMMON_SET|Manifest: NOSIGNATURE
		flywheel-forge-1.18.2-0.6.8.a.jar                 |Flywheel                      |flywheel                      |0.6.8.a             |COMMON_SET|Manifest: NOSIGNATURE
		create-1.18.2-0.5.0.g.jar                         |Create                        |create                        |0.5.0.g             |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.7.1.jar                   |Curios API                    |curios                        |1.18.2-5.0.7.1      |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.18.2-71.1.jar                         |Patchouli                     |patchouli                     |1.18.2-71.1         |COMMON_SET|Manifest: NOSIGNATURE
		ars_nouveau-1.18.2-2.8.0.jar                      |Ars Nouveau                   |ars_nouveau                   |2.8.0               |COMMON_SET|Manifest: NOSIGNATURE
		blockui-1.18.2-0.0.62-ALPHA (1).jar               |UI Library Mod                |blockui                       |1.18.2-0.0.62-ALPHA |COMMON_SET|Manifest: NOSIGNATURE
		pamhc2foodcore-1.18.2-1.0.3.jar                   |Pam's HarvestCraft 2 - Food Co|pamhc2foodcore                |1.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		create-stuff-additions1.18.2_v2.0.2a.jar          |Create Stuff & Additions      |create_sa                     |2.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		collective-1.18.2-6.26.jar                        |Collective                    |collective                    |6.26                |COMMON_SET|Manifest: NOSIGNATURE
		horse_colors-1.18.2-1.8.0.jar                     |Realistic Horse Genetics      |horse_colors                  |1.18.2-1.8.0        |COMMON_SET|Manifest: NOSIGNATURE
		AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              |COMMON_SET|Manifest: NOSIGNATURE
		Quark-3.2-358.jar                                 |Quark                         |quark                         |3.2-358             |COMMON_SET|Manifest: NOSIGNATURE
		EarthMobs-1.18.2-1.3.1.jar                        |Earth Mobs Mod                |earthmobsmod                  |1.18.2-1.3.1        |COMMON_SET|Manifest: NOSIGNATURE
		InfinityMending-1.17-0.1.0.jar                    |InfinityMending               |infinitymending               |0.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		structurize-1.18.2-1.0.424-ALPHA.jar              |Structurize                   |structurize                   |1.18.2-1.0.424-ALPHA|COMMON_SET|Manifest: NOSIGNATURE
		multi-piston-1.18.2-1.2.15-ALPHA (1).jar          |Multi-Piston                  |multipiston                   |1.18.2-1.2.15-ALPHA |COMMON_SET|Manifest: NOSIGNATURE
		minecolonies-1.18.2-1.0.1197-ALPHA.jar            |MineColonies                  |minecolonies                  |1.18.2-1.0.1197-ALPH|COMMON_SET|Manifest: NOSIGNATURE
		cfm-7.0.0-pre29-1.18.2.jar                        |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre29         |COMMON_SET|Manifest: NOSIGNATURE
		architectury-4.10.88-forge.jar                    |Architectury                  |architectury                  |4.10.88             |COMMON_SET|Manifest: NOSIGNATURE
		minecraft-comes-alive-7.4.0+1.18.2-universal.jar  |Minecraft Comes Alive         |mca                           |7.4.0+1.18.2        |COMMON_SET|Manifest: NOSIGNATURE
		appleskin-forge-mc1.18.2-2.4.1.jar                |AppleSkin                     |appleskin                     |2.4.1+mc1.18.2      |COMMON_SET|Manifest: NOSIGNATURE
		AI-Improvements-1.18.2-0.5.2.jar                  |AI-Improvements               |aiimprovements                |0.5.2               |COMMON_SET|Manifest: NOSIGNATURE
		SoL-Carrot-1.18.1-1.12.0.jar                      |Spice of Life: Carrot Edition |solcarrot                     |1.18.1-1.12.0       |COMMON_SET|Manifest: NOSIGNATURE
		light-overlay-6.0.5-forge.jar                     |Light Overlay                 |lightoverlay                  |6.0.5               |COMMON_SET|Manifest: NOSIGNATURE
		Aquaculture-1.18.2-2.3.10.jar                     |Aquaculture 2                 |aquaculture                   |1.18.2-2.3.10       |COMMON_SET|Manifest: NOSIGNATURE
		sulfurpotassiummod-1.18.2-2.3.3+Forge.jar         |Sulfur & Potassium Mod        |sulfurpotassiummod            |2.3.3               |COMMON_SET|Manifest: NOSIGNATURE
		exoticbirds-1.18.2-1.8.0.jar                      |Exotic Birds                  |exoticbirds                   |1.8.0               |COMMON_SET|Manifest: NOSIGNATURE
		DynamicTrees-1.18.2-0.11.0-Beta5.jar              |Dynamic Trees                 |dynamictrees                  |1.18.2-0.11.0-Beta5 |COMMON_SET|Manifest: NOSIGNATURE
		DynamicTreesBOP-1.18.2-3.0.0-Beta1.jar            |Dynamic Trees for Biomes o' Pl|dtbop                         |1.18.2-3.0.0-Beta1  |COMMON_SET|Manifest: NOSIGNATURE
		DynamicTreesQuark-1.18.2-2.2.1.jar                |Dynamic Trees for Quark       |dtquark                       |1.18.2-2.2.1        |COMMON_SET|Manifest: NOSIGNATURE
		dttectonic-1.1.0.jar                              |Dynamic Trees for Tectonic    |dttectonic                    |1.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		dttectonicbop-1.1.0.jar                           |Dynamic Trees for Tectonic plu|dttectonicbop                 |1.1.0               |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 403a2fdd-737d-437a-a4c6-f6633198ebf1
	FML: 40.2
	Forge: net.minecraftforge:40.2.0

**Comment by seymourimadeit** [comment]
Does this crash happen repeatedly?

**Comment by Arasarhood** [comment]
seymourimadeit,Crash occurred once while running on a server, and then again when attempting to start the server. There’s a ton of mods running on the server, so doubt we will find the cause. Just wanted to provide the info to y’all since the crash report included a link to your GitHub.Thanks,RobSent from my iPhoneOn Apr 9, 2023, at 3:38 PM, seymourimadeit ***@***.***> wrote:﻿
Does this crash happen repeatedly?

**Comment by seymourimadeit** [comment]
Since this issue hasn't been sent by anyone else regarding the 1.18 version and due to the fact 1.18 is unsupported I will have to close this.

If there is a high influx of people with this issue I will investigate further.

**Comment by seymourimadeit** [comment]
> Since this issue hasn't been sent by anyone else regarding the 1.18 version and due to the fact 1.18 is unsupported I will have to close this.
> 
> If there is a high influx of people with this issue I will investigate further.

This is also coupled along with the fact there is a highly likely chance of another mod conflicting with this one and the fact it doesn't really occur repeatedly atleast from what you're telling me
