### ISSUE TITLE
Unknown target reason

### ISSUE THREAD

**Issue by Pendrag00n** [seymourimadeit/guardvillagers#128]
Running on Java 17.0.8 (Debian 12)
**Magma version:** 1.19.3-6e6ce905
**Bukkit version:** v1_19_R2
**Forge version:** 44.1.23

I'm having the same issue as #84 but in Magma 1.19.2.
Whenever I get close enough to a village these warnings pop up on the console:

`
[03Aug2023 23:10:53.904] [Server thread/WARN] [Minecraft/]: Unknown target reason, please report on the issue tracker
java.lang.Exception: null
	at net.minecraft.world.entity.Mob.setTarget(Mob.java:235) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.Mob.m_6710_(Mob.java:225) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at tallestegg.guardvillagers.HandlerEvents.onEntityTarget(HandlerEvents.java:47) ~[guardvillagers-1.19.3-1.5.5.jar%23144!/:1.19.3-1.5.5]
	at tallestegg.guardvillagers.__HandlerEvents_onEntityTarget_LivingChangeTargetEvent.invoke(.dynamic) ~[guardvillagers-1.19.3-1.5.5.jar%23144!/:1.19.3-1.5.5]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%232!/:?]
	at net.minecraftforge.common.ForgeHooks.onLivingChangeTarget(ForgeHooks.java:259) ~[forge-1.19.3-44.1.23-universal.jar%23178!/:?]
	at net.minecraft.world.entity.Mob.setTarget(Mob.java:252) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.ai.goal.target.NearestAttackableTargetGoal.m_8056_(NearestAttackableTargetGoal.java:67) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.ai.goal.WrappedGoal.m_8056_(WrappedGoal.java:41) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_25373_(GoalSelector.java:107) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:802) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:3069) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:567) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.monster.Monster.m_8107_(Monster.java:42) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.monster.Zombie.m_8107_(Zombie.java:248) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2807) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:357) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.monster.Zombie.m_8119_(Zombie.java:221) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:775) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:653) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:385) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:365) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1318) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:383) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1235) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:1046) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:307) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[03Aug2023 23:10:53.911] [Server thread/WARN] [Minecraft/]: Unknown target reason, please report on the issue tracker
java.lang.Exception: null
	at net.minecraft.world.entity.Mob.setTarget(Mob.java:235) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.Mob.m_6710_(Mob.java:225) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at tallestegg.guardvillagers.entities.Guard.m_6710_(Guard.java:735) ~[guardvillagers-1.19.3-1.5.5.jar%23144!/:1.19.3-1.5.5]
	at tallestegg.guardvillagers.HandlerEvents.onEntityTarget(HandlerEvents.java:47) ~[guardvillagers-1.19.3-1.5.5.jar%23144!/:1.19.3-1.5.5]
	at tallestegg.guardvillagers.__HandlerEvents_onEntityTarget_LivingChangeTargetEvent.invoke(.dynamic) ~[guardvillagers-1.19.3-1.5.5.jar%23144!/:1.19.3-1.5.5]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%232!/:?]
	at net.minecraftforge.common.ForgeHooks.onLivingChangeTarget(ForgeHooks.java:259) ~[forge-1.19.3-44.1.23-universal.jar%23178!/:?]
	at net.minecraft.world.entity.Mob.setTarget(Mob.java:252) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.ai.goal.target.NearestAttackableTargetGoal.m_8056_(NearestAttackableTargetGoal.java:67) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.ai.goal.WrappedGoal.m_8056_(WrappedGoal.java:41) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_25373_(GoalSelector.java:107) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:802) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:3069) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:567) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.monster.Monster.m_8107_(Monster.java:42) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.monster.Zombie.m_8107_(Zombie.java:248) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2807) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:357) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.monster.Zombie.m_8119_(Zombie.java:221) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:775) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:653) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:385) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:365) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1318) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:383) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1235) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:1046) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:307) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[03Aug2023 23:10:53.924] [Server thread/WARN] [Minecraft/]: Unknown target reason, please report on the issue tracker
java.lang.Exception: null
	at net.minecraft.world.entity.Mob.setTarget(Mob.java:235) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.Mob.m_6710_(Mob.java:225) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at tallestegg.guardvillagers.entities.Guard.m_6710_(Guard.java:735) ~[guardvillagers-1.19.3-1.5.5.jar%23144!/:1.19.3-1.5.5]
	at tallestegg.guardvillagers.HandlerEvents.onEntityTarget(HandlerEvents.java:47) ~[guardvillagers-1.19.3-1.5.5.jar%23144!/:1.19.3-1.5.5]
	at tallestegg.guardvillagers.__HandlerEvents_onEntityTarget_LivingChangeTargetEvent.invoke(.dynamic) ~[guardvillagers-1.19.3-1.5.5.jar%23144!/:1.19.3-1.5.5]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%232!/:?]
	at net.minecraftforge.common.ForgeHooks.onLivingChangeTarget(ForgeHooks.java:259) ~[forge-1.19.3-44.1.23-universal.jar%23178!/:?]
	at net.minecraft.world.entity.Mob.setTarget(Mob.java:252) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.ai.goal.target.NearestAttackableTargetGoal.m_8056_(NearestAttackableTargetGoal.java:67) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.ai.goal.WrappedGoal.m_8056_(WrappedGoal.java:41) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_25373_(GoalSelector.java:107) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:802) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:3069) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:567) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.monster.Monster.m_8107_(Monster.java:42) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.monster.Zombie.m_8107_(Zombie.java:248) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2807) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:357) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.entity.monster.Zombie.m_8119_(Zombie.java:221) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:775) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:653) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:385) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:365) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1318) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:383) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1235) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:1046) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:307) ~[server-1.19.3-20221207.122022-srg.jar%23173!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
`

Please let me know if this is a magma issue so that I can report it to them instead

**Comment by seymourimadeit** [comment]
Honestly I'm beginning to believe this is a magma issue since "target reason" doesn't exist in base game forge minecraft. Test it on a non-magma environment and see if the same error appears. If it doesn't then it's a magma issue.
