### ISSUE TITLE
Crash with Bumblezone v7

### ISSUE THREAD

**Issue by AngellusMortis** [seymourimadeit/guardvillagers#143]
Bumblezone 7.0.16
Guard Villagers 1.6.2
Minecraft 1.20.1
Forge 77.2.1

```
java.lang.ClassCastException: class com.telepathicgrunt.the_bumblezone.entities.nonliving.SentryWatcherEntity cannot be cast to class net.minecraft.world.entity.Mob (com.telepathicgrunt.the_bumblezone.entities.nonliving.SentryWatcherEntity is in module the_bumblezone@7.0.16+1.20.1-forge of loader 'TRANSFORMER' @35af1558; net.minecraft.world.entity.Mob is in module minecraft@1.20.1 of loader 'TRANSFORMER' @35af1558)
	at tallestegg.guardvillagers.HandlerEvents.onLivingSpawned(HandlerEvents.java:96) ~[guardvillagers-1.20-1.6.2.jar%23640!/:1.20-1.6.2] {re:classloading,pl:rei_plugin_compatibilities:B}
	at tallestegg.guardvillagers.__HandlerEvents_onLivingSpawned_EntityJoinLevelEvent.invoke(.dynamic) ~[guardvillagers-1.20-1.6.2.jar%23640!/:1.20-1.6.2] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157538_(PersistentEntitySectionManager.java:79) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.PersistentEntitySectionManagerAccessor,pl:mixin:A}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157604_(PersistentEntitySectionManager.java:121) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.PersistentEntitySectionManagerAccessor,pl:mixin:A}
	at net.minecraft.world.entity.EntityType$1.m_147060_(EntityType.java:585) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at java.util.Optional.map(Optional.java:260) ~[?:?] {re:mixin}
	at net.minecraft.world.entity.EntityType.m_20645_(EntityType.java:563) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:mixin,xf:fml:forge:forge_method_redirector,re:classloading,pl:rei_plugin_compatibilities:B,xf:fml:forge:forge_method_redirector,pl:mixin:APP:the_bumblezone-common.mixins.json:entities.EntityTypeMixin,pl:mixin:APP:architectury-common.mixins.json:inject.MixinEntityType,pl:mixin:A}
	at net.minecraft.world.entity.EntityType$1.m_147056_(EntityType.java:584) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602) ~[?:?] {}
	at net.minecraft.world.entity.EntityType$1.tryAdvance(EntityType.java:583) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at java.util.Spliterator.forEachRemaining(Spliterator.java:332) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157559_(PersistentEntitySectionManager.java:120) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.PersistentEntitySectionManagerAccessor,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_143327_(ServerLevel.java:1434) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:the_bumblezone-common.mixins.json:world.ServerWorldMixin,pl:mixin:APP:krypton.mixins.json:server.fastchunkentityaccess.ServerWorldMixin,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinServerLevel,pl:mixin:APP:neruina-common.mixins.json:ServerWorldMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:aether.mixins.json:common.accessor.ServerLevelAccessor,pl:mixin:APP:roughlyenoughresources.mixins.json:MixinServerWorld,pl:mixin:APP:peripheralworks.mixins.json:ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.level.ChunkMap.m_143064_(ChunkMap.java:690) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.paper_chunk_patches.ChunkMapMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.chunk_deadlock.ChunkMapLoadMixin,pl:mixin:APP:krypton.mixins.json:shared.network.avoidwork.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:krypton.mixins.json:shared.network.flushconsolidation.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:ae2.mixins.json:chunkloading.ChunkMapMixin,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:APP:canary.mixins.json:world.player_chunk_tick.ChunkMapMixin,pl:mixin:APP:railways.mixins.json:ChunkMapAccessor,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.ChunkMapMixin,pl:mixin:A}
	at net.minecraft.server.level.ChunkMap.m_214898_(ChunkMap.java:707) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.paper_chunk_patches.ChunkMapMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.chunk_deadlock.ChunkMapLoadMixin,pl:mixin:APP:krypton.mixins.json:shared.network.avoidwork.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:krypton.mixins.json:shared.network.flushconsolidation.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:ae2.mixins.json:chunkloading.ChunkMapMixin,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:APP:canary.mixins.json:world.player_chunk_tick.ChunkMapMixin,pl:mixin:APP:railways.mixins.json:ChunkMapAccessor,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.ChunkMapMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.LevelChunk.m_62952_(LevelChunk.java:438) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelChunkMixin,pl:mixin:APP:lootr.mixins.json:MixinLevelChunk,pl:mixin:APP:neruina-common.mixins.json:WorldChunkMixin,pl:mixin:APP:canary.mixins.json:world.combined_heightmap_update.LevelChunkMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelChunkMixin,pl:mixin:APP:moonlight-common.mixins.json:LevelChunkMixin,pl:mixin:A}
	at net.minecraft.server.level.ChunkMap.mixinextras$bridge$m_62952_$158(ChunkMap.java) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.paper_chunk_patches.ChunkMapMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.chunk_deadlock.ChunkMapLoadMixin,pl:mixin:APP:krypton.mixins.json:shared.network.avoidwork.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:krypton.mixins.json:shared.network.flushconsolidation.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:ae2.mixins.json:chunkloading.ChunkMapMixin,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:APP:canary.mixins.json:world.player_chunk_tick.ChunkMapMixin,pl:mixin:APP:railways.mixins.json:ChunkMapAccessor,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.ChunkMapMixin,pl:mixin:A}
	at net.minecraft.server.level.ChunkMap.wrapOperation$zcg000$setCurrentLoadingThenPostLoad(ChunkMap.java:1905) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.paper_chunk_patches.ChunkMapMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.chunk_deadlock.ChunkMapLoadMixin,pl:mixin:APP:krypton.mixins.json:shared.network.avoidwork.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:krypton.mixins.json:shared.network.flushconsolidation.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:ae2.mixins.json:chunkloading.ChunkMapMixin,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:APP:canary.mixins.json:world.player_chunk_tick.ChunkMapMixin,pl:mixin:APP:railways.mixins.json:ChunkMapAccessor,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.ChunkMapMixin,pl:mixin:A}
	at net.minecraft.server.level.ChunkMap.m_214854_(ChunkMap.java:715) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.paper_chunk_patches.ChunkMapMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.chunk_deadlock.ChunkMapLoadMixin,pl:mixin:APP:krypton.mixins.json:shared.network.avoidwork.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:krypton.mixins.json:shared.network.flushconsolidation.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:ae2.mixins.json:chunkloading.ChunkMapMixin,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:APP:canary.mixins.json:world.player_chunk_tick.ChunkMapMixin,pl:mixin:APP:railways.mixins.json:ChunkMapAccessor,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.ChunkMapMixin,pl:mixin:A}
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[datafixerupper-6.0.8.jar%2377!/:?] {re:mixin}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar%2377!/:?] {}
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[datafixerupper-6.0.8.jar%2377!/:?] {re:mixin}
	at net.minecraft.server.level.ChunkMap.m_287044_(ChunkMap.java:699) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.paper_chunk_patches.ChunkMapMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.chunk_deadlock.ChunkMapLoadMixin,pl:mixin:APP:krypton.mixins.json:shared.network.avoidwork.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:krypton.mixins.json:shared.network.flushconsolidation.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:ae2.mixins.json:chunkloading.ChunkMapMixin,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:APP:ftbchunks-common.mixins.json:ChunkMapMixin,pl:mixin:APP:canary.mixins.json:world.player_chunk_tick.ChunkMapMixin,pl:mixin:APP:railways.mixins.json:ChunkMapAccessor,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.ChunkMapMixin,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:541) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:549) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
	at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:269) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:cupboard.mixins.json:ChunkLoadDebug,pl:mixin:APP:smoothchunk.mixins.json:ServerChunkCacheMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_ticking.ServerChunkCacheMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.ServerChunkCacheMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerChunkCacheMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.chunk_deadlock.ServerChunkCache_CurrentLoadingMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:758) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:bcc.mixins.json:MinecraftServerMixinn,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:neruina-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:roughlyenoughresources.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:bcc.mixins.json:MinecraftServerMixinn,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:neruina-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:roughlyenoughresources.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:bcc.mixins.json:MinecraftServerMixinn,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:neruina-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:roughlyenoughresources.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:bcc.mixins.json:MinecraftServerMixinn,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:neruina-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:roughlyenoughresources.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23821!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:bcc.mixins.json:MinecraftServerMixinn,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:neruina-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:roughlyenoughresources.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
```

**Comment by AngellusMortis** [comment]
No pressure, but when do you plan to push that fix out?
