### ISSUE TITLE
InvalidModFileException: Missing License, please supply a license.

### ISSUE THREAD

**Issue by hattrickpatrick** [seymourimadeit/guardvillagers#24]
Trying to launch a server with GuardVillagers mod and this message is causing an error/crash.

```[01Sep2020 07:22:02.826] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.loading.moddiscovery.InvalidModFileException: Missing License, please supply a license. (guardvillagers-1.16.1-1.1.1.jar)
[01Sep2020 07:22:02.826] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.moddiscovery.ModFileInfo.lambda$new$2(ModFileInfo.java:71)
[01Sep2020 07:22:02.826] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.Optional.orElseThrow(Unknown Source)
[01Sep2020 07:22:02.826] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.moddiscovery.ModFileInfo.<init>(ModFileInfo.java:71)
[01Sep2020 07:22:02.826] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.moddiscovery.ModFileParser.modsTomlParser(ModFileParser.java:62)
[01Sep2020 07:22:02.842] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.moddiscovery.ModFileParser.readModList(ModFileParser.java:46)
[01Sep2020 07:22:02.842] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.moddiscovery.ModFile.identifyMods(ModFile.java:114)
[01Sep2020 07:22:02.842] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:116)
[01Sep2020 07:22:02.842] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:213)
[01Sep2020 07:22:02.842] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.runScan(FMLServiceProvider.java:107)
[01Sep2020 07:22:02.842] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:111)
[01Sep2020 07:22:02.842] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:115)
[01Sep2020 07:22:02.842] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
[01Sep2020 07:22:02.842] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
[01Sep2020 07:22:02.842] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[01Sep2020 07:22:02.842] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[01Sep2020 07:22:02.842] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
[01Sep2020 07:22:02.842] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[01Sep2020 07:22:02.842] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.stream.ReferencePipeline.collect(Unknown Source)
[01Sep2020 07:22:02.842] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:116)
[01Sep2020 07:22:02.842] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:63)
[01Sep2020 07:22:02.842] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[01Sep2020 07:22:02.842] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[01Sep2020 07:22:02.842] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[01Sep2020 07:22:02.842] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[01Sep2020 07:22:02.842] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
```

Forge version: forge-1.16.2-33.0.31
GuardVillagers version: guardvillagers-1.16.1-1.1.1

If there is any other info I can provide to help I'm happy to.

**Comment by hattrickpatrick** [comment]
I just realized the mod is for 1.16.1. My mistake. I can't archive the issue report so I'm just posting this comment as an acknowledgement.
