### ISSUE TITLE
Guard Villager Disappearing After giving weapons

### ISSUE THREAD

**Issue by RAILUXUS** [seymourimadeit/guardvillagers#56]
Hi im having a problem to the mod, latest version 1.18.1 every time im giving weapon to the villager they just disappear. they become green glowing dust. please help

**Comment by seymourimadeit** [comment]
Please send a latest.log

**Comment by RAILUXUS** [comment]
[21:56:51] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[21:56:52] [Render thread/INFO]: Setting user: Railuxus
[21:56:52] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[21:56:54] [Render thread/INFO]: Narrator library for x64 successfully loaded
[21:56:55] [Render thread/INFO]: Reloading ResourceManager: Default
[21:56:59] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speakers (Realtek(R) Audio)
[21:56:59] [Render thread/INFO]: Sound engine started
[21:57:00] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[21:57:00] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[21:57:00] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[21:57:00] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[21:57:00] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[21:57:00] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[21:57:00] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[21:57:00] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[21:57:00] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[21:57:00] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[21:57:09] [Server Pinger #1/ERROR]: Can't ping  10.63.1.176: Unknown host
[21:57:15] [Render thread/INFO]: Stopping!

**Comment by seymourimadeit** [comment]
Can I also have your debug.log also

**Comment by RAILUXUS** [comment]
sorry im new is this the debug you where looking for?
![debugMC](https://user-images.githubusercontent.com/96626067/147400998-1ab74ba9-0316-46dd-bf6b-8af4d9d0c106.PNG)

**Comment by seymourimadeit** [comment]
No. I meant the debug.log in your logs folder. Please recreate the bug and send the debug.log after

**Comment by RAILUXUS** [comment]
sorry im a newbie is this the one ? theres no other file in my logs

here's whats inside the file

[12:08:17] [main/INFO]: ModLauncher running: args [--username, Railuxus, --version, forge-39.0.8, --gameDir, C:\Users\Owner\curseforge\minecraft\Instances\railux, --assetsDir, C:\Users\Owner\curseforge\minecraft\Install\assets, --assetIndex, 1.18, --uuid, 5181b33e805942098f0e675a6e5dd52c, --accessToken, ????????, --clientId, YjNkNGYxMWYtNTEwMC00MjVkLThjZDQtNzUyOTJhNjZhNjc2, --xuid, 2535460603511534, --userType, msa, --versionType, release, --width, 1024, --height, 768, --launchTarget, forgeclient, --fml.forgeVersion, 39.0.8, --fml.mcVersion, 1.18.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20211210.034407]
[12:08:17] [main/INFO]: ModLauncher 9.0.7+91+master.8569cdf starting: java version 17.0.1 by Microsoft
[12:08:17] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Owner/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2319! Service=ModLauncher Env=CLIENT
[12:08:17] [main/WARN]: Configuration file C:\Users\Owner\curseforge\minecraft\Instances\railux\config\fml.toml is not correct. Correcting
[12:08:17] [main/WARN]: Incorrect key [defaultConfigPath] was corrected from null to defaultconfigs
[12:08:17] [main/INFO]: Found mod file guardvillagers-1.18.1.4.0.jar of type MOD with locator {mods folder locator at C:\Users\Owner\curseforge\minecraft\Instances\railux\mods}
[12:08:17] [main/INFO]: Found mod file fmlcore-1.18.1-39.0.8.jar of type LIBRARY with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@22db8f4
[12:08:17] [main/INFO]: Found mod file javafmllanguage-1.18.1-39.0.8.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@22db8f4
[12:08:17] [main/INFO]: Found mod file mclanguage-1.18.1-39.0.8.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@22db8f4
[12:08:17] [main/INFO]: Found mod file client-1.18.1-20211210.034407-srg.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@22db8f4
[12:08:17] [main/INFO]: Found mod file forge-1.18.1-39.0.8-universal.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@22db8f4
[12:08:18] [main/INFO]: Launching target 'forgeclient' with arguments [--version, forge-39.0.8, --gameDir, C:\Users\Owner\curseforge\minecraft\Instances\railux, --assetsDir, C:\Users\Owner\curseforge\minecraft\Install\assets, --uuid, 5181b33e805942098f0e675a6e5dd52c, --username, Railuxus, --assetIndex, 1.18, --accessToken, ????????, --clientId, YjNkNGYxMWYtNTEwMC00MjVkLThjZDQtNzUyOTJhNjZhNjc2, --xuid, 2535460603511534, --userType, msa, --versionType, release, --width, 1024, --height, 768]
[12:08:22] [Render thread/WARN]: Assets URL 'union:/C:/Users/Owner/curseforge/minecraft/Install/libraries/net/minecraft/client/1.18.1-20211210.034407/client-1.18.1-20211210.034407-srg.jar%2353!/assets/.mcassetsroot' uses unexpected schema
[12:08:22] [Render thread/WARN]: Assets URL 'union:/C:/Users/Owner/curseforge/minecraft/Install/libraries/net/minecraft/client/1.18.1-20211210.034407/client-1.18.1-20211210.034407-srg.jar%2353!/data/.mcassetsroot' uses unexpected schema
[12:08:22] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[12:08:24] [Render thread/INFO]: Setting user: Railuxus
[12:08:24] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT
[12:08:27] [modloading-worker-0/INFO]: Forge mod loading, version 39.0.8, for MC 1.18.1 with MCP 20211210.034407
[12:08:27] [modloading-worker-0/INFO]: MinecraftForge v39.0.8 Initialized
[12:08:29] [Render thread/INFO]: Narrator library for x64 successfully loaded
[12:08:29] [Render thread/INFO]: Reloading ResourceManager: Default, Mod Resources
[12:08:29] [modloading-worker-0/WARN]: Configuration file C:\Users\Owner\curseforge\minecraft\Instances\railux\config\guardvillagers-client.toml is not correct. Correcting
[12:08:29] [modloading-worker-0/WARN]: Incorrect key Have guards use the steve model? was corrected from null to its default, false. 
[12:08:29] [modloading-worker-0/WARN]: Configuration file C:\Users\Owner\curseforge\minecraft\Instances\railux\config\forge-client.toml is not correct. Correcting
[12:08:29] [modloading-worker-0/WARN]: Incorrect key client was corrected from null to its default, SimpleCommentedConfig:{}. 
[12:08:29] [modloading-worker-0/WARN]: Incorrect key client.alwaysSetupTerrainOffThread was corrected from null to its default, false. 
[12:08:29] [modloading-worker-0/WARN]: Incorrect key client.experimentalForgeLightPipelineEnabled was corrected from null to its default, false. 
[12:08:29] [modloading-worker-0/WARN]: Incorrect key client.showLoadWarnings was corrected from null to its default, true. 
[12:08:29] [modloading-worker-0/WARN]: Incorrect key client.useCombinedDepthStencilAttachment was corrected from null to its default, false. 
[12:08:29] [modloading-worker-0/WARN]: Incorrect key client.forceSystemNanoTime was corrected from null to its default, false. 
[12:08:29] [modloading-worker-0/WARN]: Configuration file C:\Users\Owner\curseforge\minecraft\Instances\railux\config\guardvillagers-common.toml is not correct. Correcting
[12:08:29] [modloading-worker-0/WARN]: Incorrect key Illagers in raids attack animals? was corrected from null to its default, false. 
[12:08:29] [modloading-worker-0/WARN]: Incorrect key Witches attack villagers? was corrected from null to its default, true. 
[12:08:29] [modloading-worker-0/WARN]: Incorrect key Have illusioners in raids? was corrected from null to its default, true. 
[12:08:29] [modloading-worker-0/WARN]: Incorrect key Guards attack all mobs? was corrected from null to its default, false. 
[12:08:29] [modloading-worker-0/WARN]: Incorrect key Mob BlackList was corrected from null to its default, []. 
[12:08:29] [modloading-worker-0/WARN]: Incorrect key Have Villagers have some common sense? was corrected from null to its default, true. 
[12:08:29] [modloading-worker-0/WARN]: Incorrect key Have Illagers have some common sense? was corrected from null to its default, true. 
[12:08:29] [modloading-worker-0/WARN]: Incorrect key Have Guards have some common sense? was corrected from null to its default, false. 
[12:08:29] [modloading-worker-0/WARN]: Incorrect key Have Guards open doors? was corrected from null to its default, true. 
[12:08:29] [modloading-worker-0/WARN]: Incorrect key Have Guards raise their shield all the time? was corrected from null to its default, false. 
[12:08:29] [modloading-worker-0/WARN]: Incorrect key Have guards form a phalanx? was corrected from null to its default, true. 
[12:08:29] [modloading-worker-0/WARN]: Incorrect key Have guards attempt to avoid firing into other friendlies? (Experimental) was corrected from null to its default, false. 
[12:08:29] [modloading-worker-0/WARN]: Incorrect key Make it so players have to have hero of the village to convert villagers into guards? was corrected from null to its default, false. 
[12:08:29] [modloading-worker-0/WARN]: Incorrect key Have it so blacksmiths heal golems under 60 health? was corrected from null to its default, true. 
[12:08:29] [modloading-worker-0/WARN]: Incorrect key Have it so clerics heal guards and players with hero of the village? was corrected from null to its default, true. 
[12:08:29] [modloading-worker-0/WARN]: Incorrect key Range was corrected from null to its default, 50.0. 
[12:08:29] [modloading-worker-0/WARN]: Incorrect key Guard health regeneration amount was corrected from null to its default, 1.0. 
[12:08:29] [modloading-worker-0/WARN]: Incorrect key Allow guard arrows to damage villagers, iron golems, or other guards? The i-frames will still be shown for them but they won't lose any health if this is set to false was corrected from null to its default, true. 
[12:08:29] [modloading-worker-0/WARN]: Incorrect key Allow armorers and weaponsmiths repair guard items when down below half durability? was corrected from null to its default, true. 
[12:08:29] [modloading-worker-0/WARN]: Incorrect key Allow players to give guards stuff only if they have the hero of the village effect? was corrected from null to its default, true. 
[12:08:29] [modloading-worker-0/WARN]: Incorrect key Allow players to set guard patrol points only if they have hero of the village was corrected from null to its default, true. 
[12:08:29] [modloading-worker-0/WARN]: Configuration file C:\Users\Owner\curseforge\minecraft\Instances\railux\config\forge-common.toml is not correct. Correcting
[12:08:29] [modloading-worker-0/WARN]: Incorrect key general was corrected from null to its default, SimpleCommentedConfig:{}. 
[12:08:29] [modloading-worker-0/WARN]: Incorrect key general.defaultWorldType was corrected from null to its default, default. 
[12:08:30] [Forge Version Check/INFO]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[12:08:31] [Forge Version Check/INFO]: [forge] Found status: BETA Current: 39.0.8 Target: 39.0.8
[12:08:31] [Forge Version Check/INFO]: [guardvillagers] Starting version check at https://raw.githubusercontent.com/seymourimadeit/guardvillagers/master/update.json
[12:08:31] [Forge Version Check/INFO]: [guardvillagers] Found status: UP_TO_DATE Current: 1.4.0 Target: null
[12:08:40] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speakers (Realtek(R) Audio)
[12:08:40] [Render thread/INFO]: Sound engine started
[12:08:40] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[12:08:40] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[12:08:40] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[12:08:40] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[12:08:40] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[12:08:40] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[12:08:40] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[12:08:42] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[12:08:42] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[12:08:42] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[12:11:04] [Render thread/INFO]: Connecting to mac.com, 25565
[12:11:25] [Server Connector #1/ERROR]: Couldn't connect to server
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: mac.com/17.146.233.11:25565
Caused by: java.net.ConnectException: Connection timed out: no further information
	at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
	at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946) ~[?:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.68.Final.jar%2332!:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:11:50] [Render thread/INFO]: Connecting to mac.com, 25565
[12:13:01] [Server Pinger #1/ERROR]: Can't ping  10.63.1.176: Unknown host
[12:13:31] [Render thread/INFO]: Stopping!

![debug folder](https://user-images.githubusercontent.com/96626067/147401467-98251a37-0591-4bad-b04d-fd1bbdd5b867.PNG)

**Comment by seymourimadeit** [comment]
I noticed that in the ingame screenshot you sent eariler that it says that you're in a "vanilla" server, try to change that into a forge server and see if the guard conversion works properly.

**Comment by RAILUXUS** [comment]
thanks , uhm can i still run my save file in vanilla server and turn it into forge server? how can i convert it to forge server thanks

**Comment by seymourimadeit** [comment]
You're gonna have to go to another person for that as I don't have much experience with servers.
Preferably ask here https://discord.gg/forge.

If the mod still doesn't work even after you make the server a forge one please comment on this issue and I will reopen it.
