### ISSUE TITLE
Small error.

### ISSUE THREAD

**Issue by Hempfest** [seymourimadeit/guardvillagers#84]
Magma: 1.16.5
This doesnt stop us from playing and enjoying the game but it said to report it to the issue tracker so here you go:
```
[04:25:44] [Server thread/WARN] [Minecraft/]: Unknown target reason, please report on the issue tracker
java.lang.Exception: null
        at net.minecraft.entity.MobEntity.setAttackTarget(MobEntity.java:228) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.MobEntity.func_70624_b(MobEntity.java:216) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        at tallestegg.guardvillagers.HandlerEvents.onEntityHurt(HandlerEvents.java:72) ~[guardvillagers:1.16.5.1.2.6] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_81_HandlerEvents_onEntityHurt_LivingHurtEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:363) ~[forge:?] {re:classloading}
        at net.minecraft.entity.LivingEntity.damageEntityCB(LivingEntity.java:1791) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cavesandcliffs.mixins.json:common.entity.LivingEntityMixin,pl:mixin:APP:cavesandcliffs.mixins.json:core.accessor.LivingEntityAccessor,pl:mixin:APP:mostructures.mixins.json:MixinLivingEntity,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:endergetic.mixins.json:LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:1206) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cavesandcliffs.mixins.json:common.entity.LivingEntityMixin,pl:mixin:APP:cavesandcliffs.mixins.json:core.accessor.LivingEntityAccessor,pl:mixin:APP:mostructures.mixins.json:MixinLivingEntity,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:endergetic.mixins.json:LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at com.github.alexthe666.alexsmobs.entity.EntityRaccoon$AIStealFromVillagers.func_75246_d(EntityRaccoon.java:679) ~[alexsmobs:1.12.1] {re:classloading}
        at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_312] {}
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_312] {}
        at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_312] {re:computing_frames}
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_312] {}
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_312] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_312] {}
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_312] {}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_312] {}
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_312] {}
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_312] {}
        at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:88) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:761) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2827) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cavesandcliffs.mixins.json:common.entity.LivingEntityMixin,pl:mixin:APP:cavesandcliffs.mixins.json:core.accessor.LivingEntityAccessor,pl:mixin:APP:mostructures.mixins.json:MixinLivingEntity,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:endergetic.mixins.json:LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:552) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.AgeableEntity.func_70636_d(AgeableEntity.java:142) ~[?:?] {re:mixin,re:classloading}
        at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:53) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:byg.mixins.json:common.entity.MixinAnimalEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2571) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cavesandcliffs.mixins.json:common.entity.LivingEntityMixin,pl:mixin:APP:cavesandcliffs.mixins.json:core.accessor.LivingEntityAccessor,pl:mixin:APP:mostructures.mixins.json:MixinLivingEntity,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:endergetic.mixins.json:LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:348) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        at com.github.alexthe666.alexsmobs.entity.EntityRaccoon.func_70071_h_(EntityRaccoon.java:320) ~[alexsmobs:1.12.1] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:732) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cavesandcliffs.mixins.json:common.world.gen.ServerWorldMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.World.func_217390_a(World.java:742) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:505) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cavesandcliffs.mixins.json:common.world.gen.ServerWorldMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1118) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:381) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1032) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:869) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:286) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312] {}
[04:25:44] [Server thread/WARN] [Minecraft/]: Unknown target reason, please report on the issue tracker
java.lang.Exception: null
        at net.minecraft.entity.MobEntity.setAttackTarget(MobEntity.java:228) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.MobEntity.func_70624_b(MobEntity.java:216) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        at tallestegg.guardvillagers.HandlerEvents.onEntityHurt(HandlerEvents.java:72) ~[guardvillagers:1.16.5.1.2.6] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_81_HandlerEvents_onEntityHurt_LivingHurtEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:363) ~[forge:?] {re:classloading}
        at net.minecraft.entity.LivingEntity.damageEntityCB(LivingEntity.java:1791) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cavesandcliffs.mixins.json:common.entity.LivingEntityMixin,pl:mixin:APP:cavesandcliffs.mixins.json:core.accessor.LivingEntityAccessor,pl:mixin:APP:mostructures.mixins.json:MixinLivingEntity,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:endergetic.mixins.json:LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:1206) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cavesandcliffs.mixins.json:common.entity.LivingEntityMixin,pl:mixin:APP:cavesandcliffs.mixins.json:core.accessor.LivingEntityAccessor,pl:mixin:APP:mostructures.mixins.json:MixinLivingEntity,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:endergetic.mixins.json:LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at com.github.alexthe666.alexsmobs.entity.EntityRaccoon$AIStealFromVillagers.func_75246_d(EntityRaccoon.java:679) ~[alexsmobs:1.12.1] {re:classloading}
        at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_312] {}
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_312] {}
        at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_312] {re:computing_frames}
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_312] {}
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_312] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_312] {}
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_312] {}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_312] {}
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_312] {}
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_312] {}
        at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:88) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:761) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2827) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cavesandcliffs.mixins.json:common.entity.LivingEntityMixin,pl:mixin:APP:cavesandcliffs.mixins.json:core.accessor.LivingEntityAccessor,pl:mixin:APP:mostructures.mixins.json:MixinLivingEntity,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:endergetic.mixins.json:LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:552) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.AgeableEntity.func_70636_d(AgeableEntity.java:142) ~[?:?] {re:mixin,re:classloading}
        at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:53) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:byg.mixins.json:common.entity.MixinAnimalEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2571) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cavesandcliffs.mixins.json:common.entity.LivingEntityMixin,pl:mixin:APP:cavesandcliffs.mixins.json:core.accessor.LivingEntityAccessor,pl:mixin:APP:mostructures.mixins.json:MixinLivingEntity,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:endergetic.mixins.json:LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:348) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        at com.github.alexthe666.alexsmobs.entity.EntityRaccoon.func_70071_h_(EntityRaccoon.java:320) ~[alexsmobs:1.12.1] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:732) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cavesandcliffs.mixins.json:common.world.gen.ServerWorldMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.World.func_217390_a(World.java:742) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:505) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cavesandcliffs.mixins.json:common.world.gen.ServerWorldMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1118) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:381) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1032) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:869) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:286) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312] {}
```

**Comment by seymourimadeit** [comment]
1.16.5 is not supported anymore. Please try to recreate this bug in the latest versions and I will investigate further.
